### ISSUE TITLE
Update to nf-core/bacass v2.3.0 and Adjust Paths

### ISSUE THREAD

**Issue by Daniel-VM** [BU-ISCIII/buisciii-tools#283]
There is a new version of nf-core/bacass: [v2.3.0](https://github.com/nf-core/bacass/releases/tag/2.3.0). This version includes the integration of KmerFinder and custom MultiQC. The remaining tasks are:

- [ ] Set up the latest version in the `pipelines/` folder by cloning it directly from the[ nf-core/bacass repository](https://github.com/nf-core/bacass/tree/2.3.0) (since the current version is from a forked repo).
- [ ] Update Nextflow Run Path: Adjust the nextflow run path in the affected templates/lablogs (i.e: assembly) to reflect the updated directory.
- [ ] Update the repo URL in `services.json`

**Comment by victor5lm** [comment]
- [X] Set up the latest version in the `pipelines/` folder by cloning it directly from the[ nf-core/bacass repository](https://github.com/nf-core/bacass/tree/2.3.0) (since the current version is from a forked repo).
* Both `pipelines` and `pipelines_new` folders have the latest version of bacass.
- [X] Update Nextflow Run Path: Adjust the nextflow run path in the affected templates/lablogs (i.e: assembly) to reflect the updated directory.
* Assembly's `lablog` file has been updated.
- [X] Update the repo URL in `services.json`
* `services.json` has been updated with the new repo URL.
